
---
- name: Validate DNS on all nodes
  hosts: all
  become: true
  tasks:
    - name: Ensure DNS resolution for rancher.example.com
      shell: getent hosts rancher.example.com
      register: dns_check
      failed_when: dns_check.rc != 0
      changed_when: false

- name: Validate and configure HAProxy
  hosts: haproxy
  become: true
  tasks:
    - name: Generate HAProxy configuration with Rancher masters
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
        enabled: true

- name: Install RKE2 server on masters
  hosts: masters
  become: true
  tasks:
    - name: Install RKE2
      shell: |
        curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
      args:
        creates: /usr/local/bin/rke2

    - name: Create RKE2 config
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          token: mysecuretoken
          tls-san:
            - rancher.example.com
          node-taint: []
          disable:
            - rke2-ingress-nginx
      notify: Restart RKE2

    - name: Enable and start RKE2 server
      systemd:
        name: rke2-server
        enabled: yes
        state: started

  handlers:
    - name: Restart RKE2
      systemd:
        name: rke2-server
        state: restarted

- name: Install Helm and cert-manager
  hosts: masters[0]
  become: true
  tasks:
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Add Helm repositories
      shell: |
        helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
        helm repo add jetstack https://charts.jetstack.io
        helm repo update

    - name: Install cert-manager
      shell: |
        kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -
        helm install cert-manager jetstack/cert-manager --namespace cert-manager --set installCRDs=true --version v1.12.4
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Install Rancher with Helm
  hosts: masters[0]
  become: true
  tasks:
    - name: Install Rancher
      shell: |
        kubectl create namespace cattle-system --dry-run=client -o yaml | kubectl apply -f -
        helm install rancher rancher-latest/rancher \
          --namespace cattle-system \
          --set hostname=rancher.example.com \
          --set replicas=3 \
          --set ingress.tls.source=self-signed
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Wait for Rancher deployment
      shell: kubectl -n cattle-system rollout status deploy/rancher
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Copy kubeconfig for Rancher API usage
      fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: ./rancher-kubeconfig.yaml
        flat: yes

    - name: Test Rancher API
      uri:
        url: https://rancher.example.com/v3
        method: GET
        validate_certs: no
        return_content: yes
      register: rancher_api

    - name: Debug Rancher API response
      debug:
        var: rancher_api.status
