- name: Phase 2 - Join remaining masters using extracted token
  hosts: masters[1:]
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Fetch RKE2 cluster token from primary master
      delegate_to: "{{ groups['masters'][0] }}"
      slurp:
        src: /var/lib/rancher/rke2/server/node-token
      register: token_file

    - name: Decode and register token
      set_fact:
        rke2_cluster_token: "{{ token_file.content | b64decode | trim }}"

    - name: Ensure RKE2 config directory exists
      file:
        path: /etc/rancher/rke2
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure RKE2 is installed
      shell: |
        curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
      args:
        creates: /usr/local/bin/rke2

    - name: Deploy RKE2 config with token
      template:
        src: config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'
      vars:
        token: "{{ rke2_cluster_token }}"

    - name: Enable and start RKE2 service
      systemd:
        name: rke2-server
        enabled: yes
        state: started
