- name: Phase 2 - Join remaining masters using extracted token
  hosts: masters[1:]
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Ensure DNS resolution for {{ rancher_endpoint }}
      shell: getent hosts {{ rancher_endpoint }}
      register: dns_check
      failed_when: dns_check.rc != 0
      changed_when: false
      
    - name: Fetch RKE2 cluster token from primary master
      delegate_to: "{{ groups['masters'][0] }}"
      slurp:
        src: /var/lib/rancher/rke2/server/node-token
      register: token_file

    - name: Decode and register token
      set_fact:
        rke2_cluster_token: "{{ token_file.content | b64decode | trim }}"

    - name: Ensure RKE2 config directory exists
      file:
        path: /etc/rancher/rke2
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure RKE2 is installed
      shell: |
        curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
      args:
        creates: /usr/local/bin/rke2

    - name: Deploy RKE2 config with token
      template:
        src: config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'
      vars:
        token: "{{ rke2_cluster_token }}"

    - name: Enable and start RKE2 service
      systemd:
        name: rke2-server
        enabled: yes
        state: started
  
- name: Post-installation validation
  hosts: masters[0]
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Validate Rancher pods are running
      shell: |
        kubectl get pods -n cattle-system --no-headers | grep -v Running && exit 1 || exit 0
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: rancher_pods_status
      failed_when: rancher_pods_status.rc != 0

    - name: Validate cert-manager pods are running
      shell: |
        kubectl get pods -n cert-manager --no-headers | grep -v Running && exit 1 || exit 0
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: cert_pods_status
      failed_when: cert_pods_status.rc != 0

    - name: Validate Kubernetes node status is Ready
      shell: |
        kubectl get nodes --no-headers | grep -v Ready && exit 1 || exit 0
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: node_ready_check
      failed_when: node_ready_check.rc != 0

    - name: Validate Rancher Console via curl
      uri:
        url: "https://{{ rancher_endpoint }}/dashboard"
        method: GET
        validate_certs: no
        return_content: yes
      register: rancher_console
      retries: 5
      delay: 10
      until: rancher_console.status == 200

    - name: Report Rancher Console availability
      debug:
        msg: "Rancher Console is reachable and returned status {{ rancher_console.status }}"
