
---
- name: Validate DNS on all nodes
  hosts: all
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Ensure DNS resolution for {{ rancher_endpoint }}
      shell: getent hosts {{ rancher_endpoint }}
      register: dns_check
      failed_when: dns_check.rc != 0
      changed_when: false

- name: Validate and configure HAProxy
  hosts: haproxy
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
    rancher_backend: "{{ rancher_backend }}"
    rancher_backend_console: "{{ rancher_backend_console }}"
  tasks:
    - name: Install policycoreutils-python-utils (for semanage)
      package:
        name: policycoreutils-python-utils
        state: present

    - name: Allow HAProxy to bind ports 443 and 6443 in SELinux
      ansible.posix.seport:
        ports: "{{ item }}"
        proto: tcp
        setype: http_port_t
        state: present
      loop:
        - 443
        - 6443

    - name: Generate HAProxy configuration with Rancher masters
      template:
        src: haproxy.cfg.dynamic.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
        enabled: true

- name: Install and configure RKE2 server on masters
  hosts: masters
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Ensure RKE2 is installed
      shell: |
        curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
      args:
        creates: /usr/local/bin/rke2

    - name: Ensure correct RKE2 config is deployed
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          token: mysecuretoken
          tls-san:
            - {{ rancher_endpoint }}
          node-taint: []
          disable:
            - rke2-ingress-nginx
        owner: root
        group: root
        mode: '0644'
      notify: Restart RKE2

    - name: Allow RKE2 ports in SELinux
      ansible.posix.seport:
        ports: "{{ item }}"
        proto: tcp
        setype: kube_apiserver_port_t
        state: present
      loop:
        - 6443
        - 9345

    - name: Enable and start RKE2 service
      systemd:
        name: rke2-server
        enabled: yes
        state: started

  handlers:
    - name: Restart RKE2
      systemd:
        name: rke2-server
        state: restarted

- name: Install Helm and cert-manager
  hosts: masters[0]
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Add Helm repositories
      shell: |
        helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
        helm repo add jetstack https://charts.jetstack.io
        helm repo update

    - name: Install cert-manager
      shell: |
        kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -
        helm upgrade --install cert-manager jetstack/cert-manager \
          --namespace cert-manager \
          --version v1.12.4 \
          --set installCRDs=true
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Install Rancher with Helm
  hosts: masters[0]
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Create namespace cattle-system
      shell: kubectl create namespace cattle-system --dry-run=client -o yaml | kubectl apply -f -
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Install or upgrade Rancher
      shell: |
        helm upgrade --install rancher rancher-latest/rancher \
          --namespace cattle-system \
          --set hostname={{ rancher_endpoint }} \
          --set replicas=3 \
          --set ingress.tls.source=self-signed
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Wait for Rancher deployment
      shell: kubectl -n cattle-system rollout status deploy/rancher
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Copy kubeconfig for Rancher API usage
      fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: ./rancher-kubeconfig.yaml
        flat: yes

    - name: Test Rancher API
      uri:
        url: https://{{ rancher_endpoint }}/v3
        method: GET
        validate_certs: no
        return_content: yes
      register: rancher_api

    - name: Debug Rancher API response
      debug:
        var: rancher_api.status
