- name: Phase 2 - Join remaining masters using extracted token
  hosts: masters[1:]
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Ensure DNS resolution for {{ rancher_endpoint }}
      shell: getent hosts {{ rancher_endpoint }}
      register: dns_check
      failed_when: dns_check.rc != 0
      changed_when: false
      
    - name: Fetch RKE2 cluster token from primary master
      delegate_to: "{{ groups['masters'][0] }}"
      slurp:
        src: /var/lib/rancher/rke2/server/node-token
      register: token_file

    - name: Decode and register token
      set_fact:
        rke2_cluster_token: "{{ token_file.content | b64decode | trim }}"

- name: Install and configure RKE2 server on masters
  hosts: masters
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Ensure RKE2 config directory exists
      file:
        path: /etc/rancher/rke2
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure RKE2 is installed
      shell: |
        curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
      args:
        creates: /usr/local/bin/rke2

    - name: Ensure correct RKE2 config is deployed
      template:
        src: config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'
      vars:
        token: "{{ rke2_cluster_token }}"
      notify: Restart RKE2

    - name: Allow port 6443 for Kubernetes API manually
      command: semanage port -a -t http_port_t -p tcp "{{ item }}"
      ignore_errors: yes
      when: ansible_selinux.status == "enabled"
      loop:
        - 6443
        - 9345

    - name: Enable and start RKE2 service
      systemd:
        name: rke2-server
        enabled: yes
        state: started

  handlers:
    - name: Restart RKE2
      systemd:
        name: rke2-server
        state: restarted

- name: Install Helm and cert-manager
  hosts: masters[0]
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Add Helm repositories
      shell: |
        helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
        helm repo add jetstack https://charts.jetstack.io
        helm repo update

    - name: Wait until the API Server is ready
      shell: |
        for i in $(seq 1 30); do
          kubectl get nodes && break
          sleep 10
        done
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Wait until all nodes are Ready
      shell: |
        kubectl wait --for=condition=Ready nodes --all --timeout=180s
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Install cert-manager
      shell: |
        kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -
        helm upgrade --install cert-manager jetstack/cert-manager           --namespace cert-manager           --version v1.12.4           --set installCRDs=true
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Install Rancher with Helm
  hosts: masters[0]
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Create namespace cattle-system
      shell: kubectl create namespace cattle-system --dry-run=client -o yaml | kubectl apply -f -
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Install or upgrade Rancher
      shell: |
        helm upgrade --install rancher rancher-latest/rancher           --namespace cattle-system           --set hostname={{ rancher_endpoint }}           --set replicas=3           --set ingress.tls.source=self-signed
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Wait for Rancher deployment
      shell: kubectl -n cattle-system rollout status deploy/rancher
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Copy kubeconfig for Rancher API usage
      fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: ./rancher-kubeconfig.yaml
        flat: yes

    - name: Test Rancher API
      uri:
        url: https://{{ rancher_endpoint }}/v3
        method: GET
        validate_certs: no
        return_content: yes
      register: rancher_api

    - name: Debug Rancher API response
      debug:
        var: rancher_api.status

- name: Post-installation validation
  hosts: masters[0]
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
  tasks:
    - name: Validate Rancher pods are running
      shell: |
        kubectl get pods -n cattle-system --no-headers | grep -v Running && exit 1 || exit 0
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: rancher_pods_status
      failed_when: rancher_pods_status.rc != 0

    - name: Validate cert-manager pods are running
      shell: |
        kubectl get pods -n cert-manager --no-headers | grep -v Running && exit 1 || exit 0
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: cert_pods_status
      failed_when: cert_pods_status.rc != 0

    - name: Validate Kubernetes node status is Ready
      shell: |
        kubectl get nodes --no-headers | grep -v Ready && exit 1 || exit 0
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: node_ready_check
      failed_when: node_ready_check.rc != 0

    - name: Validate Rancher Console via curl
      uri:
        url: "https://{{ rancher_endpoint }}/dashboard"
        method: GET
        validate_certs: no
        return_content: yes
      register: rancher_console
      retries: 5
      delay: 10
      until: rancher_console.status == 200

    - name: Report Rancher Console availability
      debug:
        msg: "Rancher Console is reachable and returned status {{ rancher_console.status }}"
