
---
- name: Validate and configure HAProxy
  hosts: haproxy
  become: true
  vars:
    rancher_endpoint: "{{ rancher_endpoint }}"
    rancher_backend: "{{ rancher_backend }}"
    rancher_backend_console: "{{ rancher_backend_console }}"
  tasks:
    - name: Ensure DNS resolution for {{ rancher_endpoint }}
      shell: getent hosts {{ rancher_endpoint }}
      register: dns_check
      failed_when: dns_check.rc != 0
      changed_when: false
      
    - name: Install policycoreutils-python-utils (for semanage)
      package:
        name: policycoreutils-python-utils
        state: present

    - name: Allow port 6443 for Kubernetes API manually
      command: semanage port -a -t http_port_t -p tcp "{{ item }}"
      ignore_errors: yes
      when: ansible_selinux.status == "enabled"
      loop:
        - 6443
        - 9345

    - name: Generate HAProxy configuration with Rancher masters
      template:
        src: haproxy.cfg.dynamic.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
        enabled: true

